run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      Main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/esivanov203/antibruteforce/internal/service
          - github.com/esivanov203/antibruteforce/internal/model
          - github.com/gorilla/handlers
          - github.com/gorilla/mux
          - github.com/benbjohnson/clock
          - github.com/joho/godotenv
          - github.com/esivanov203/antibruteforce/internal/httpapi
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/esivanov203/antibruteforce/internal/service
          - github.com/esivanov203/antibruteforce/internal/model
          - github.com/stretchr/testify/require
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/mock
          - github.com/benbjohnson/clock

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar       # вместо exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused           # включает замену для deadcode/varcheck/structcheck
    - wastedassign
    - whitespace

version: "1"
